---

- name: Clone app repo
  git: repo={{git_repo_url}} dest={{git_repo_dir}} version={{git_repo_branch}}

- name: Clear pip build dir
  file: path=/opt/venv/build state=absent

- name: Create a virtual env and install app requirements
  pip: requirements='requirements/production.txt' virtualenv=/opt/venv chdir={{git_repo_dir}}

- name: Install extra python libraries
  pip: name={{item}} virtualenv=/opt/venv state=latest
  with_items:
    - pylibmc
    - raven
    - cssmin

- name: Run collectstatic
  django_manage: >
      command=collectstatic
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars

- name: Run syncdb
  django_manage: >
      command=syncdb
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars

- name: Run DB migrations
  django_manage: >
      command=migrate
      app_path={{django_project_dir}}
      settings=launcher.settings.production
      pythonpath={{django_project_dir}}
      virtualenv={{venv_dir}}
  environment: django_env_vars

#- name: Run offline compression of the assets
#  django_manage: >
#      command=compress
#      app_path={{git_repo_dir}}
#      settings=launcher.settings.production
#      pythonpath={{git_repo_dir}}
#      virtualenv=/opt/venv
#  notify:
#    - reload supervisor config
