---

- name: Ensure Python development tools are available
  apt: pkg={{item}} state=latest
  with_items:
    - python-dev
    - python-setuptools
    - python-pycurl

- name: Install pip
  easy_install: name=pip

- name: Update python-setuptools
  pip: name=setuptools state=latest extra_args='--no-use-wheel'

- name: Install virtualenv.
  pip: name=virtualenv state=latest

- name: Add node.js repo
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Install node.ks
  apt: name=nodejs state=latest

- name: Install Bower
  npm: name=bower global=yes state=latest
