---

- name: start supervisor
  action: service name=supervisord state=started

- name: restart supervisor
  action: service name=supervisord state=restarted

- name: reload supervisor config
  command: supervisorctl update
