---

- name: Update APT
  apt: update_cache=yes cache_valid_time=3600

- name: Install common packages
  apt: pkg={{item}} state=present
  with_items:
    - vim
    - git-core
    - gcc
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - htop
    - iotop

- name: Generate locales
  command: locale-gen hr_HR.UTF-8
