---
- name: install packages needed for single server
  apt: pkg={{item}} install_recommends=yes state=present
  with_items:
    - supervisor

- name: Install supervisord
  pip: name=supervisor state=latest

- name: Create a config folder for supervisor
  file: path=/etc/log/supervisor state=directory

- name: Create a conf.d folder for supervisor
  file: path=/etc/log/supervisor/ state=directory

- name: Create a log folder for supervisor
  file: path=/etc/supervisor/conf.d state=directory

- name: Copy supervisor configuration file
  template: src=supervisord.conf dest=/etc/supervisor/supervisord.conf
  notify:
    - reload supervisor config

- name: Copy launcher configuration file
  template: src=launcher.conf dest=/etc/supervisor/conf.d/launcher.conf
  notify:
    - reload supervisor config

- name: Start supervisord
  service: name=supervisord state=started
